version: '3.3'
name: foodgram-sprint14
services:

  backend:
    build:
      context: ../backend/foodgram_backend
      dockerfile: Dockerfile
    restart: always
    volumes:
       - static_volume:/app/static
       - media_volume:/app/media

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  web-nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      # - static_volume:/usr/share/nginx/html/static
      # - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
